# Generated by Django 5.1.7 on 2025-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='send_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
