# Generated by Django 5.1.7 on 2025-04-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_send_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
