# Generated by Django 5.1.7 on 2025-04-02 00:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='message_attachments/', validators=[api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
