# Generated by Django 5.1.7 on 2025-04-02 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_subscription_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='difficulties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('include_all_courses', models.BooleanField(default=False)),
                ('included_difficulties', models.JSONField(blank=True, default=list)),
                ('features', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('active_courses', models.ManyToManyField(blank=True, to='api.course')),
                ('included_categories', models.ManyToManyField(blank=True, to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscriptionpackage'),
        ),
    ]
