# Generated by Django 5.1.7 on 2025-04-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_subscription_difficulties_subscriptionpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
