# Generated by Django 5.2 on 2025-04-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_courseresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlibrary',
            old_name='course',
            new_name='Course',
        ),
        migrations.AddField(
            model_name='courseresource',
            name='downloa_d_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
