# Generated by Django 5.2 on 2025-04-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_assignment_assignmentfile_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='test_content_html',
            field=models.TextField(blank=True, help_text='Test questions or content (legacy HTML format)', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='test_type',
            field=models.CharField(choices=[('quiz', 'Multiple Choice Quiz'), ('essay', 'Essay Questions'), ('sheet', 'Interactive Worksheet'), ('code', 'Coding Exercise'), ('mixed', 'Mixed Format')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='test_content',
            field=models.JSONField(blank=True, help_text='Structured test content in JSON format', null=True),
        ),
    ]
