# Generated by Django 5.2 on 2025-04-11 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_assignment_test_content_html_assignment_test_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='test_content_html',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='test_type',
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='added_via_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscription'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='test_content',
            field=models.TextField(blank=True, help_text='Test questions or content', null=True),
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('percentage_complete', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='api.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lecture')},
            },
        ),
    ]
