# Generated by Django 5.2 on 2025-04-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_notification_options_notification_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='due_date',
        ),
    ]
