# Generated by Django 5.2 on 2025-04-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_quiz_lecture_quiz_show_after_lecture_studentprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('ms_teams', 'Microsoft Teams'), ('webex', 'WebEx'), ('google_meet', 'Google Meet'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
