# Generated by Django 5.2 on 2025-04-22 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_event_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('font_size', models.IntegerField(default=16)),
                ('high_contrast', models.BooleanField(default=False)),
                ('color_theme', models.CharField(default='default', max_length=20)),
                ('density', models.CharField(default='comfortable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Appearance Setting',
                'verbose_name_plural': 'User Appearance Settings',
            },
        ),
    ]
