# Generated by Django 5.2 on 2025-04-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_assignment_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('text', 'Text Answer'), ('file_upload', 'File Upload')], default='multiple_choice', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, help_text='Options for multiple choice questions', null=True)),
                ('correct_feedback', models.TextField(blank=True, null=True)),
                ('incorrect_feedback', models.TextField(blank=True, null=True)),
                ('sample_answer', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.assignment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
