# Generated by Django 5.2 on 2025-04-26 08:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_assignmentquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='show_after_lecture',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(9999, 12, 30, 23, 59, 59), null=True),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('checkbox', 'Checkbox')], default='multiple_choice', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, help_text='Options for multiple choice questions', null=True)),
                ('correct_feedback', models.TextField(blank=True, null=True)),
                ('incorrect_feedback', models.TextField(blank=True, null=True)),
                ('sample_answer', models.TextField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
