# Generated by Django 5.2 on 2025-04-26 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_quiz_lecture_remove_quiz_show_after_lecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lecture',
            field=models.ForeignKey(blank=True, help_text='The lecture this quiz belongs to. Leave blank if assigning to a course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.lecture'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course this quiz belongs to. Leave blank if assigning to a lecture.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.course'),
        ),
    ]
