# Generated by Django 5.2 on 2025-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_quizsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('checkbox', 'Checkbox'), ('sentence_building', 'Sentence Building')], default='multiple_choice', max_length=50),
        ),
    ]
