# Generated by Django 5.2 on 2025-05-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_certificatefile_certificatetemplate'), 
    ]

    operations = [
        migrations.AddField(
            model_name='certificatefile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certs/'),
        ),
    ]
