# Generated by Django 5.2 on 2025-05-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_clean_features_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpackage',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
